### ISSUE TITLE
Undefined method 'HostnameDialog' in firstboot_hostname.rb

### ISSUE THREAD

**Issue by lbssousa** [yast/yast-firstboot#39]
It seems that HostnameDialog is gone from https://github.com/yast/yast-network/commits/master/src/include/network/services/dns.rb since commit [b0d16ed](https://github.com/yast/yast-network/commit/b0d16ed4642d2c6ad59dee60e127d58ca6c835c9).

**Comment by AvengerMoJo** [comment]
I just saw the same error in wfm.rb:229 backtrace to firstboot_hostname.rb:62 in kiwi firstboot image

**Comment by rogeroberholtzer** [comment]
Is the intention that the hostname only be set in the network setup? Meaning that a system not on the network can't be assigned a name that will be used for other than network related tasks?

**Comment by mchf** [comment]
On Po, zář 18, 2017 at 11:45:53 -0700, Roger Oberholtzer wrote:
>Is the intention that the hostname only be set in the network setup? Meaning that a system not on the network can't be assigned a name that will be used for other than network related tasks?

I'm not sure if I got the question correctly. However, yast2-network is
AFAIK the only yast module which sets Hostname (in /etc/hostname and/or
in /etc/hosts).

Michal Filka

**Comment by mchf** [comment]
Hostname dialog was resurrected in yast2-firstboot 4.0.1. It is no longer needed in yast2-network, so we migrated it there.
